<?php

const IMAGE_BASE_FOLDER = APP_BASE.'/images';
CONST IMAGE_SRC_FOLDER = IMAGE_BASE_FOLDER.'/src/';
CONST IMAGE_DUPS_FOLDER = IMAGE_BASE_FOLDER.'/dups/';
CONST IMAGE_UNIQUE_FOLDER = IMAGE_BASE_FOLDER.'/unique/';

CONST ARCHIVE_FOLDER = APP_BASE.'/archives/';